# ==========================================
# API Version and Kind define what type of Kubernetes resource this is.
apiVersion: v1
kind: Secret
# Metadata stores identification info (name and labels) used for internal lookup.
metadata:
  name: food-secrets
type: Opaque
data:
  DB_PASSWORD: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  JWT_SECRET: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  RABBITMQ_DEFAULT_USER: "Z3Vlc3Q="
  RABBITMQ_DEFAULT_PASS: "Z3Vlc3Q="