# ==========================================
# API Version and Kind define what type of Kubernetes resource this is.
apiVersion: v1
kind: Service
# Metadata stores identification info (name and labels) used for internal lookup.
metadata:
  name: prometheus-service
# SPEC (Specification) describes exactly how you want this item to behave.
spec:
  type: NodePort
  # SELECTOR: The 'lookup logic' that connects this manager to the actual Pods.
  selector:
    app: prometheus
  # Network interface linking virtual Cluster ports to internal container ports.
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30002